// ==============================================================================
// notification_service.dart - Local Push Notification Service
// ==============================================================================
// This service manages local push notifications on the device.
// It sends alerts for:
// - Budget warnings (80%, 90%, 100% of budget used)
// - Category budget overruns
// - Achievement unlocks
// - Level ups
// - Streak milestones
// - Daily spending summaries
// - Tracking reminders
// - Recurring transaction (bill) reminders
//
// Key concepts:
// - "Local" notifications are generated by the app itself (not from a server)
// - Each notification has a unique ID so it can be updated/cancelled individually
// - Notifications are organized into "channels" (Android) for user control
// - Channels: budget_alerts, achievement_unlocked, level_up, streak_milestone,
//   recurring_reminders
//
// Uses the flutter_local_notifications package for cross-platform notifications.
// ==============================================================================

import 'package:flutter/foundation.dart';                                        // For debugPrint (only prints in debug mode, not release)
import 'package:flutter_local_notifications/flutter_local_notifications.dart'; // Notification plugin
import 'package:shared_preferences/shared_preferences.dart';  // For saving notification settings
import 'package:intl/intl.dart';                               // For date formatting
import 'dart:convert';                                          // For json.encode (notification payload)
import '../models/budget_model.dart';                           // Budget model for budget alerts
import '../models/gamification_model.dart';                     // NewAchievement model

class NotificationService {
  // ==============================================================================
  // Plugin Instance and State
  // ==============================================================================
  // FlutterLocalNotificationsPlugin is the main entry point for all notification operations.
  // _initialized flag prevents initializing the plugin multiple times.
  // ==============================================================================
  static final FlutterLocalNotificationsPlugin _notifications =
      FlutterLocalNotificationsPlugin();

  static bool _initialized = false;    // Track if plugin has been initialized

  // ==============================================================================
  // initialize - Set Up the Notification Plugin
  // ==============================================================================
  // Must be called before showing any notifications.
  // Configures platform-specific settings for Android and iOS.
  //
  // AndroidInitializationSettings: Specifies the notification icon
  //   '@mipmap/ic_launcher' = the app's launcher icon
  //
  // DarwinInitializationSettings (iOS):
  //   Requests permission to show alerts, badges, and play sounds
  //
  // The _initialized flag ensures this only runs once even if called multiple times.
  // ==============================================================================
  static Future<void> initialize() async {
    if (_initialized) return;          // Already initialized, skip

    // Android notification settings
    const androidSettings = AndroidInitializationSettings('@mipmap/ic_launcher');

    // iOS notification settings (Darwin = Apple's OS kernel name)
    const iosSettings = DarwinInitializationSettings(
      requestAlertPermission: true,    // Ask to show alert popups
      requestBadgePermission: true,    // Ask to show badge numbers on app icon
      requestSoundPermission: true,    // Ask to play notification sounds
    );

    // Combine platform settings
    const initializationSettings = InitializationSettings(
      android: androidSettings,
      iOS: iosSettings,
    );

    // Initialize the plugin with the settings
    await _notifications.initialize(initializationSettings);
    _initialized = true;
  }

  // ==============================================================================
  // BUDGET NOTIFICATIONS
  // ==============================================================================

  // ==============================================================================
  // showBudgetAlert - Show a Budget-Related Notification
  // ==============================================================================
  // Creates and displays a notification in the "budget_alerts" channel.
  //
  // NotificationDetails configures how the notification looks and behaves:
  // - channelId: Groups notifications for user control (Android Settings)
  // - importance/priority: HIGH makes the notification pop up on screen
  // - ticker: Text shown in the status bar briefly
  //
  // notificationId: Each notification needs a unique int ID.
  // Using the same ID updates the existing notification instead of creating a new one.
  // ==============================================================================
  static Future<void> showBudgetAlert({
    required String title,
    required String body,
    required int notificationId,
  }) async {
    await initialize();                 // Ensure plugin is initialized

    // Android-specific notification appearance
    const androidDetails = AndroidNotificationDetails(
      'budget_alerts',                  // Channel ID (unique identifier)
      'Budget Alerts',                  // Channel name (shown in Android Settings)
      channelDescription: 'Alerts for budget spending and limits',
      importance: Importance.high,      // HIGH = shows as popup
      priority: Priority.high,          // HIGH = treated as urgent
      ticker: 'Budget Alert',          // Brief text in status bar
    );

    // iOS-specific notification appearance
    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,               // Show the notification alert
      presentBadge: true,               // Update the app badge count
      presentSound: true,               // Play a sound
    );

    // Combine both platform details
    const notificationDetails = NotificationDetails(
      android: androidDetails,
      iOS: iosDetails,
    );

    // Show the notification
    await _notifications.show(
      notificationId,                   // Unique ID for this notification
      title,                            // Notification title
      body,                             // Notification body text
      notificationDetails,              // Platform-specific appearance
    );
  }

  // ==============================================================================
  // checkBudgetAndAlert - Analyze Budget and Send Appropriate Alerts
  // ==============================================================================
  // Checks the budget usage percentage and sends different alerts:
  // - 100%+ (exceeded): Red alert notification
  // - 90-99% (warning): Yellow warning notification
  // - 80-89% (caution): Blue caution notification
  //
  // Also checks each individual category for overruns.
  //
  // Notification IDs:
  // - 1000-1002: Overall budget alerts
  // - 2000+: Individual category alerts (incremented per category)
  // ==============================================================================
  static Future<void> checkBudgetAndAlert(BudgetModel budget) async {
    final percentage = budget.percentageUsed;     // Get the overall usage percentage

    // Alert for overall budget status
    // isOverBudget is derived from percentageUsed >= 100, so we check it directly
    // (the old condition `percentage >= 100 && !budget.isOverBudget` was always false)
    if (budget.isOverBudget) {
      // Budget has been exceeded
      await showBudgetAlert(
        title: '🚨 Budget Exceeded!',
        body: 'You\'ve spent RM ${budget.totalSpent.toStringAsFixed(2)} of your RM ${budget.totalBudget.toStringAsFixed(2)} budget.',
        notificationId: 1000,
      );
    } else if (percentage >= 90 && percentage < 100) {
      // Approaching limit (90-99%)
      await showBudgetAlert(
        title: '⚠️ Budget Warning',
        body: 'You\'ve used ${percentage.toStringAsFixed(0)}% of your monthly budget. RM ${budget.totalRemaining.toStringAsFixed(2)} remaining.',
        notificationId: 1001,
      );
    } else if (percentage >= 80 && percentage < 90) {
      // Caution (80-89%)
      await showBudgetAlert(
        title: '📊 Budget Alert',
        body: 'You\'ve spent ${percentage.toStringAsFixed(0)}% of your budget. Watch your spending!',
        notificationId: 1002,
      );
    }

    // Check each individual category budget
    int categoryAlertId = 2000;        // Starting ID for category alerts
    for (var category in budget.categories) {
      if (category.isOverBudget) {
        // Category exceeded its allocated budget
        await showBudgetAlert(
          title: '🚨 ${category.categoryName} Over Budget',
          body: 'You\'ve exceeded your ${category.categoryName} budget by RM ${(-category.remaining).toStringAsFixed(2)}.',
          // -category.remaining gives the amount over budget (remaining is negative when over)
          notificationId: categoryAlertId++,    // Post-increment: use value, then add 1
        );
      } else if (category.percentageUsed >= 90) {
        // Category approaching its limit (90%+)
        await showBudgetAlert(
          title: '⚠️ ${category.categoryName} Warning',
          body: '${category.percentageUsed.toStringAsFixed(0)}% of ${category.categoryName} budget used. RM ${category.remaining.toStringAsFixed(2)} remaining.',
          notificationId: categoryAlertId++,
        );
      }
    }
  }

  // ==============================================================================
  // Convenience Notification Methods
  // ==============================================================================
  // Quick-access methods for common notification types.
  // ==============================================================================

  // Show a daily spending summary notification
  static Future<void> showDailySummary({
    required double todaySpending,
    required double monthlyBudget,
  }) async {
    await initialize();

    await showBudgetAlert(
      title: '📈 Daily Summary',
      body: 'You spent RM ${todaySpending.toStringAsFixed(2)} today. Monthly budget: RM ${monthlyBudget.toStringAsFixed(2)}.',
      notificationId: 3000,
    );
  }

  // Show a reminder to track expenses
  static Future<void> showTrackingReminder() async {
    await initialize();

    await showBudgetAlert(
      title: '💡 Don\'t forget!',
      body: 'Have you logged all your expenses today?',
      notificationId: 4000,
    );
  }

  // ==============================================================================
  // GAMIFICATION NOTIFICATIONS
  // ==============================================================================

  // ==============================================================================
  // showAchievementUnlocked - Show Achievement Unlock Notification
  // ==============================================================================
  // Uses the "achievement_unlocked" notification channel.
  // Displayed when a user earns a new achievement.
  // ==============================================================================
  static Future<void> showAchievementUnlocked({
    required String achievementName,
    required int xpEarned,
    required int notificationId,
  }) async {
    await initialize();

    const androidDetails = AndroidNotificationDetails(
      'achievement_unlocked',           // Channel for achievements
      'Achievements',
      channelDescription: 'Notifications for unlocked achievements',
      importance: Importance.high,
      priority: Priority.high,
      ticker: 'Achievement Unlocked',
    );

    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );

    const notificationDetails = NotificationDetails(
      android: androidDetails,
      iOS: iosDetails,
    );

    await _notifications.show(
      notificationId,
      '🏆 Achievement Unlocked!',
      '$achievementName - $xpEarned XP earned!',
      notificationDetails,
    );
  }

  // ==============================================================================
  // showLevelUp - Show Level Up Notification
  // ==============================================================================
  // Displayed when a user earns enough XP to reach a new level.
  // ==============================================================================
  static Future<void> showLevelUp({
    required int newLevel,
    required int notificationId,
  }) async {
    await initialize();

    const androidDetails = AndroidNotificationDetails(
      'level_up',                       // Channel for level ups
      'Level Up',
      channelDescription: 'Notifications for level progression',
      importance: Importance.high,
      priority: Priority.high,
      ticker: 'Level Up',
    );

    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );

    const notificationDetails = NotificationDetails(
      android: androidDetails,
      iOS: iosDetails,
    );

    await _notifications.show(
      notificationId,
      '⭐ Level Up!',
      'Congratulations! You\'ve reached Level $newLevel!',
      notificationDetails,
    );
  }

  // ==============================================================================
  // showStreakMilestone - Show Streak Milestone Notification
  // ==============================================================================
  // Displayed when a user reaches a notable streak milestone
  // (e.g., 7 days, 30 days of consistent tracking).
  // ==============================================================================
  static Future<void> showStreakMilestone({
    required int streakDays,
    required int notificationId,
  }) async {
    await initialize();

    const androidDetails = AndroidNotificationDetails(
      'streak_milestone',               // Channel for streak milestones
      'Streak Milestones',
      channelDescription: 'Notifications for streak achievements',
      importance: Importance.high,
      priority: Priority.high,
      ticker: 'Streak Milestone',
    );

    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );

    const notificationDetails = NotificationDetails(
      android: androidDetails,
      iOS: iosDetails,
    );

    await _notifications.show(
      notificationId,
      '🔥 Streak Milestone!',
      'Amazing! You\'re on a $streakDays-day streak!',
      notificationDetails,
    );
  }

  // ==============================================================================
  // checkAndNotifyAchievements - Show Notifications for Newly Unlocked Achievements
  // ==============================================================================
  // Called after checkAchievements API returns newly unlocked achievements.
  // Shows one notification per new achievement.
  //
  // Notification IDs start at 5000 and increment for each achievement.
  // ==============================================================================
  static Future<void> checkAndNotifyAchievements(List<NewAchievement> newlyUnlocked) async {
    if (newlyUnlocked.isEmpty) return;    // No new achievements, nothing to show

    int notificationId = 5000;
    for (var newAchievement in newlyUnlocked) {
      await showAchievementUnlocked(
        achievementName: newAchievement.achievement.name,
        xpEarned: newAchievement.xpEarned,
        notificationId: notificationId++,    // Unique ID for each achievement
      );
    }
  }

  // ==============================================================================
  // Notification Management
  // ==============================================================================

  // Cancel ALL notifications (clear everything)
  static Future<void> cancelAll() async {
    await _notifications.cancelAll();
  }

  // Cancel a specific notification by its ID
  static Future<void> cancel(int notificationId) async {
    await _notifications.cancel(notificationId);
  }

  // ============================================================================
  // BILL REMINDERS & RECURRING TRANSACTION NOTIFICATIONS
  // ============================================================================

  // ==============================================================================
  // requestPermissions - Request Notification Permissions (Android 13+ and iOS)
  // ==============================================================================
  // Android 13+ (API 33+) requires the POST_NOTIFICATIONS runtime permission.
  // The user sees a system dialog: "Allow SmartFinance to send notifications?"
  // Without this, notifications are silently blocked on Android 13+ devices.
  //
  // iOS also requires explicit permission — same behavior as before.
  //
  // resolvePlatformSpecificImplementation<T>() returns the platform plugin
  // instance (Android or iOS) — returns null if on the other platform.
  // ?. is null-safe call — skips the call if the implementation doesn't exist.
  // ==============================================================================
  static Future<bool> requestPermissions() async {
    if (!_initialized) await initialize();

    // --- Android 13+ (API 33+): Request POST_NOTIFICATIONS runtime permission ---
    // On Android 12 and below this call is a no-op (permission auto-granted).
    // On Android 13+ it shows the system "Allow Notifications?" dialog once.
    final androidPlugin = _notifications
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>();
    if (androidPlugin != null) {
      await androidPlugin.requestNotificationsPermission();
    }

    // --- iOS: Request permission to show alerts, badges, and play sounds ---
    final result = await _notifications
        .resolvePlatformSpecificImplementation<IOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(alert: true, badge: true, sound: true);

    return result ?? true; // Default true — Android returns null here but is handled above
  }

  // ==============================================================================
  // scheduleRecurringReminder - Schedule a Bill Reminder Notification
  // ==============================================================================
  // Shows a notification reminding the user about an upcoming recurring transaction.
  //
  // Parameters:
  // - recurringId: ID of the recurring transaction (used to build notification ID)
  // - daysBeforeReminder: How many days before the due date to remind (default: 1)
  //
  // Notification ID formula: 10000 + recurringId
  // This avoids conflicts with other notification IDs (budget: 1000-2000,
  // gamification: 3000-5000, recurring: 10000+)
  //
  // Note: Currently shows immediate notifications for testing.
  // In production, you'd use zonedSchedule() for scheduled notifications.
  // ==============================================================================
  static Future<void> scheduleRecurringReminder({
    required int recurringId,
    required String name,
    required double amount,
    required String type,
    required DateTime nextExecution,
    int daysBeforeReminder = 1,
  }) async {
    await initialize();

    // Calculate when to show the reminder
    final reminderDate = nextExecution.subtract(Duration(days: daysBeforeReminder));

    // Don't schedule if the reminder date is already in the past
    if (reminderDate.isBefore(DateTime.now())) return;

    // Build unique notification ID: 10000 + recurringId
    final notificationId = 10000 + recurringId;

    const androidDetails = AndroidNotificationDetails(
      'recurring_reminders',             // Channel for bill reminders
      'Bill Reminders',
      channelDescription: 'Reminders for upcoming recurring transactions',
      importance: Importance.high,
      priority: Priority.high,
      ticker: 'Bill Reminder',
    );

    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );

    const notificationDetails = NotificationDetails(
      android: androidDetails,
      iOS: iosDetails,
    );

    // Choose emoji based on transaction type
    final typeEmoji = type.toLowerCase() == 'income' ? '💰' : '💸';
    final title = 'Upcoming $type: $name';
    final body = '$typeEmoji RM ${amount.toStringAsFixed(2)} due on ${DateFormat('MMM dd, yyyy').format(nextExecution)}';

    try {
      // Show the reminder notification immediately
      await _notifications.show(
        notificationId,
        title,
        body,
        notificationDetails,
        payload: json.encode({                  // Attach data to the notification
          'type': 'recurring_reminder',         // So the app knows what to do when tapped
          'recurringId': recurringId,
          'name': name,
        }),
      );

      debugPrint('Scheduled reminder for $name (ID: $notificationId) on $reminderDate');
    } catch (e) {
      debugPrint('Error scheduling notification: $e');
    }
  }

  // Cancel a specific recurring reminder by its recurring transaction ID
  static Future<void> cancelRecurringReminder(int recurringId) async {
    await initialize();
    final notificationId = 10000 + recurringId;    // Reconstruct the notification ID
    await _notifications.cancel(notificationId);
    debugPrint('Cancelled reminder for recurring transaction $recurringId');
  }

  // ==============================================================================
  // Notification Settings (Persistent via SharedPreferences)
  // ==============================================================================

  // Get current notification settings from device storage
  static Future<Map<String, dynamic>> getNotificationSettings() async {
    final prefs = await SharedPreferences.getInstance();
    return {
      'enabled': prefs.getBool('notifications_enabled') ?? true,       // Default: enabled
      'daysBeforeReminder': prefs.getInt('days_before_reminder') ?? 1, // Default: 1 day before
      'soundEnabled': prefs.getBool('notification_sound') ?? true,     // Default: sound on
      'vibrationEnabled': prefs.getBool('notification_vibration') ?? true, // Default: vibration on
    };
  }

  // Save notification settings to device storage
  // Only saves fields that are provided (null fields are skipped)
  static Future<void> saveNotificationSettings({
    bool? enabled,
    int? daysBeforeReminder,
    bool? soundEnabled,
    bool? vibrationEnabled,
  }) async {
    final prefs = await SharedPreferences.getInstance();
    if (enabled != null) await prefs.setBool('notifications_enabled', enabled);
    if (daysBeforeReminder != null) await prefs.setInt('days_before_reminder', daysBeforeReminder);
    if (soundEnabled != null) await prefs.setBool('notification_sound', soundEnabled);
    if (vibrationEnabled != null) await prefs.setBool('notification_vibration', vibrationEnabled);
  }

  // ==============================================================================
  // scheduleAllRecurringReminders - Schedule Reminders for All Active Recurring Transactions
  // ==============================================================================
  // Called when the app starts or when recurring transactions are updated.
  // Goes through all recurring transactions and schedules reminders for active ones.
  //
  // Checks notification settings first - if notifications are disabled, does nothing.
  // ==============================================================================
  static Future<void> scheduleAllRecurringReminders(List<Map<String, dynamic>> recurringList) async {
    final settings = await getNotificationSettings();
    if (settings['enabled'] != true) return;      // Notifications disabled, skip

    final daysBeforeReminder = settings['daysBeforeReminder'] as int;

    for (var recurring in recurringList) {
      // The API model's to_dict() returns camelCase keys (isActive, nextExecution, etc.)
      // Handle both boolean true and integer 1 (database might return either)
      final isActive = recurring['isActive'] == true || recurring['isActive'] == 1;
      if (!isActive) continue;                    // Skip inactive ones

      try {
        final nextExecutionStr = recurring['nextExecution'];
        if (nextExecutionStr == null) continue;   // Skip if no next execution date

        final nextExecution = DateTime.parse(nextExecutionStr);

        // Schedule the reminder
        await scheduleRecurringReminder(
          recurringId: recurring['recurringId'],
          name: recurring['name'] ?? 'Unnamed',
          amount: (recurring['amount'] ?? 0.0).toDouble(),
          type: recurring['transactionType'] ?? 'expense',
          nextExecution: nextExecution,
          daysBeforeReminder: daysBeforeReminder,
        );
      } catch (e) {
        debugPrint('Error scheduling reminder for recurring ${recurring['RecurringId']}: $e');
      }
    }
  }

  // ==============================================================================
  // getUpcomingReminders - Get List of Upcoming Reminders for UI Display
  // ==============================================================================
  // Returns a list of upcoming recurring transactions within the next 30 days.
  // Used to display a "Upcoming Bills" section in the UI.
  //
  // Each item includes:
  // - recurringId, name, amount, type, category
  // - nextExecution: the due date
  // - daysUntil: how many days until the due date
  //
  // Results are sorted by date (soonest first).
  // ==============================================================================
  static Future<List<Map<String, dynamic>>> getUpcomingReminders(
    List<Map<String, dynamic>> recurringList,
  ) async {
    final List<Map<String, dynamic>> upcomingReminders = [];
    final now = DateTime.now();
    final thirtyDaysFromNow = now.add(const Duration(days: 30));

    for (var recurring in recurringList) {
      // Use camelCase keys — the API model's to_dict() returns camelCase
      final isActive = recurring['isActive'] == true || recurring['isActive'] == 1;
      if (!isActive) continue;

      try {
        final nextExecutionStr = recurring['nextExecution'];
        if (nextExecutionStr == null) continue;

        final nextExecution = DateTime.parse(nextExecutionStr);

        // Only include if within the next 30 days
        if (nextExecution.isAfter(now) && nextExecution.isBefore(thirtyDaysFromNow)) {
          upcomingReminders.add({
            'recurringId': recurring['recurringId'],
            'name': recurring['name'],
            'amount': recurring['amount'],
            'type': recurring['transactionType'],
            'category': recurring['category'],
            'nextExecution': nextExecution,
            'daysUntil': nextExecution.difference(now).inDays,   // Days until due
          });
        }
      } catch (e) {
        debugPrint('Error processing recurring ${recurring['RecurringId']}: $e');
      }
    }

    // Sort by date (soonest first)
    upcomingReminders.sort((a, b) =>
      (a['nextExecution'] as DateTime).compareTo(b['nextExecution'] as DateTime)
    );

    return upcomingReminders;
  }

  // ==============================================================================
  // sendTestNotification - Send a Test Notification
  // ==============================================================================
  // Used to verify that notifications are working correctly.
  // Can be triggered from the settings screen.
  // ==============================================================================
  static Future<void> sendTestNotification() async {
    await initialize();

    await showBudgetAlert(
      title: 'Test Notification',
      body: 'Bill reminders are working! You will be notified before your recurring transactions are due.',
      notificationId: 999999,          // Special ID for test notifications
    );
  }
}
